on:
  # runs when a pull request is opened or reopened or when the head branch of the pull request is updated
  pull_request_target:

jobs:
  testfoo:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.head_ref }}

    - run: |
        echo "The action was run" >> README.md
    
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Format


