on:
  # runs when a pull request is opened or reopened or when the head branch of the pull request is updated
  pull_request_target:

jobs:
  testfoo:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The action was run


